In [1]:
# Import TensorFlow library
# TensorFlow is used for creating tensors, performing mathematical
# operations, and building deep learning models.
import tensorflow as tf

# Import NumPy
# NumPy is used here for calculating eigenvalues and eigenvectors.
import numpy as np

In [2]:
# PART 1: Creating Tensors with Different Shapes and Data Types

print("\n========== PART 1 : Tensor Creation ==========\n")

# Creating a scalar tensor (0-D tensor)
# A scalar contains only one value.
scalar = tf.constant(25)

print("Scalar Tensor:")
print(scalar)

# Creating a vector tensor (1-D tensor)
# A vector is a one-dimensional array.
vector = tf.constant([10, 20, 30, 40])

print("\nVector Tensor:")
print(vector)

# Creating a matrix tensor (2-D tensor)
# A matrix contains rows and columns.
matrix = tf.constant([[1, 2],
                      [3, 4]])

print("\nMatrix Tensor:")
print(matrix)

# Creating a 3-D tensor
# This tensor contains two matrices.
tensor3d = tf.constant([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print("\n3-D Tensor:")
print(tensor3d)

# Creating tensors with different data types

integer_tensor = tf.constant([1,2,3], dtype=tf.int32)
float_tensor = tf.constant([1.5,2.5,3.5], dtype=tf.float32)
boolean_tensor = tf.constant([True, False, True])

print("\nInteger Tensor:")
print(integer_tensor)

print("\nFloat Tensor:")
print(float_tensor)

print("\nBoolean Tensor:")
print(boolean_tensor)


========== PART 1 : Tensor Creation ==========

Scalar Tensor:
tf.Tensor(25, shape=(), dtype=int32)

Vector Tensor:
tf.Tensor([10 20 30 40], shape=(4,), dtype=int32)

Matrix Tensor:
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)

3-D Tensor:
tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)

Integer Tensor:
tf.Tensor([1 2 3], shape=(3,), dtype=int32)

Float Tensor:
tf.Tensor([1.5 2.5 3.5], shape=(3,), dtype=float32)

Boolean Tensor:
tf.Tensor([ True False  True], shape=(3,), dtype=bool)


In [3]:
# PART 2: Basic Tensor Operations

print("\n========== PART 2 : Basic Operations ==========\n")

A = tf.constant([[10,20],
                 [30,40]])

B = tf.constant([[5,10],
                 [15,20]])

# Tensor Addition
addition = tf.add(A,B)

print("Addition:")
print(addition)

# Tensor Subtraction
subtraction = tf.subtract(A,B)

print("\nSubtraction:")
print(subtraction)

# Element-wise Multiplication
multiplication = tf.multiply(A,B)

print("\nElement-wise Multiplication:")
print(multiplication)

# Element-wise Division
division = tf.divide(A,B)

print("\nDivision:")
print(division)


========== PART 2 : Basic Operations ==========

Addition:
tf.Tensor(
[[15 30]
 [45 60]], shape=(2, 2), dtype=int32)

Subtraction:
tf.Tensor(
[[ 5 10]
 [15 20]], shape=(2, 2), dtype=int32)

Element-wise Multiplication:
tf.Tensor(
[[ 50 200]
 [450 800]], shape=(2, 2), dtype=int32)

Division:
tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float64)


In [4]:
# PART 3: Reshape, Slice and Index

print("\n========== PART 3 : Reshape, Slice and Index ==========\n")

# Create a tensor having 12 elements
tensor = tf.constant([1,2,3,4,5,6,7,8,9,10,11,12])

# Reshape converts 1-D tensor into 3 rows and 4 columns
reshaped = tf.reshape(tensor,(3,4))

print("Reshaped Tensor:")
print(reshaped)

# Access first row
print("\nFirst Row:")
print(reshaped[0])

# Access second column
print("\nSecond Column:")
print(reshaped[:,1])

# Slice first two rows
print("\nFirst Two Rows:")
print(reshaped[0:2])

# Access individual element
print("\nElement at Row 2 Column 3:")
print(reshaped[1,2])


========== PART 3 : Reshape, Slice and Index ==========

Reshaped Tensor:
tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)

First Row:
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)

Second Column:
tf.Tensor([ 2  6 10], shape=(3,), dtype=int32)

First Two Rows:
tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4), dtype=int32)

Element at Row 2 Column 3:
tf.Tensor(7, shape=(), dtype=int32)


In [5]:
# PART 4: Matrix Multiplication

print("\n========== PART 4 : Matrix Multiplication ==========\n")

matrix1 = tf.constant([[1,2],
                       [3,4]])

matrix2 = tf.constant([[5,6],
                       [7,8]])

# Matrix multiplication follows row × column rule.
product = tf.matmul(matrix1,matrix2)

print("Matrix Multiplication Result:")
print(product)


========== PART 4 : Matrix Multiplication ==========

Matrix Multiplication Result:
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [6]:
# PART 5: Eigenvalues and Eigenvectors

print("\n========== PART 5 : Eigenvalues and Eigenvectors ==========\n")

# TensorFlow tensor
matrix_tf = tf.constant([[4.0,2.0],
                         [1.0,3.0]])

# Convert TensorFlow tensor into NumPy array
matrix_np = matrix_tf.numpy()

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix_np)

print("Matrix:")
print(matrix_np)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)



========== PART 5 : Eigenvalues and Eigenvectors ==========

Matrix:
[[4. 2.]
 [1. 3.]]

Eigenvalues:
[5. 2.]

Eigenvectors:
[[ 0.8944272  -0.70710677]
 [ 0.4472136   0.70710677]]


In [7]:
# PART 6: XOR Problem using TensorFlow

print("\n========== PART 6 : XOR Neural Network ==========\n")

# XOR input dataset
# Four possible combinations of two binary inputs.
X = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
], dtype=np.float32)

# Expected XOR outputs
Y = np.array([
    [0],
    [1],
    [1],
    [0]
], dtype=np.float32)

# Create Sequential Neural Network
model = tf.keras.Sequential([

    # Hidden layer with 8 neurons
    # ReLU activation introduces non-linearity.
    tf.keras.layers.Dense(8,
                          activation='relu',
                          input_shape=(2,)),

    # Output layer with Sigmoid activation
    # Produces output between 0 and 1.
    tf.keras.layers.Dense(1,
                          activation='sigmoid')
])

# Compile the model
# Adam optimizer updates weights.
# Binary Crossentropy is suitable for binary classification.
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Train the model
# epochs=1000 means the network learns from the data
# one thousand times.
model.fit(
    X,
    Y,
    epochs=1000,
    verbose=0
)

# Predict outputs
prediction = model.predict(X)

print("\nPredicted Outputs:")

for i in range(len(X)):
    print(X[i], " --> ", prediction[i][0])

print("\nRounded Predictions:")

for i in range(len(X)):
    print(X[i], " --> ", round(float(prediction[i][0])))


========== PART 6 : XOR Neural Network ==========



c:\Users\Vaibhav Singh\anaconda3\envs\tybsc_practical\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step

Predicted Outputs:
[0. 0.]  -->  0.2921542
[0. 1.]  -->  0.7997658
[1. 0.]  -->  0.8538624
[1. 1.]  -->  0.16075552

Rounded Predictions:
[0. 0.]  -->  0
[0. 1.]  -->  1
[1. 0.]  -->  1
[1. 1.]  -->  0
